In [1]:
import pandas as pd

In [2]:
import requests

In [3]:
from bs4 import BeautifulSoup

In [5]:
Product_name =[]
Prices = []
Description=[]
Reviews=[]

In [7]:
for i in range(2,10):
    url = "https://www.flipkart.com/search?q=laptops+under+20000&sid=6bo%2Cb5g&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_1_18_na_na_ps&otracker1=AS_QueryStore_OrganicAutoSuggest_1_18_na_na_ps&as-pos=1&as-type=RECENT&suggestionId=laptops+under+20000%7CLaptops&requestId=faa6291a-cd64-49bd-871c-1ffc9dc3b508&as-searchtext=laptops+under+2000&page="+str(i)
    r = requests.get(url)
    soup = BeautifulSoup(r.text, "lxml")
    box = soup.find("div",class_ = "_1YokD2 _3Mn1Gg")
    np = soup.find("a",class_ = "_1LKTO3").get("href")
    cnp = "https://www.flipkart.com"+np
    names = box.find_all("div",class_ = "_4rR01T")
    for i in names:
        name = i.text
        Product_name.append(name)
    prices = box.find_all("div",class_ = "_30jeq3 _1_WHN1")
    for i in prices:
        price = i.text
        Prices.append(price)
    desc = box.find_all("ul",class_ = "_1xgFaf")
    for i in desc:
        desc = i.text
        Description.append(desc)
    reviews = box.find_all("div",class_ = "_3LWZlK")
    for i in reviews:
        reviews = i.text
        Reviews.append(reviews)

In [8]:
print(len(Product_name))
print(len(Prices))
print(len(Description))
print(len(Reviews))

216
192
192
152

In [12]:
df = pd.DataFrame({"Prices":Prices,"Description":Description})
df.to_csv("LAPTOP.csv")

In [11]:
df = pd.DataFrame({"Product Name":Product_name})
df.to_csv("prodname.csv")

In [13]:
df = pd.DataFrame({"Reviews":Reviews})

In [14]:
df.to_csv("Reviw.csv")

In [15]:
lap = pd.read_csv("lap.csv")

In [16]:
lap

,Product Name,Prices,Description,Reviews
0,Infinix Y1 Plus Neo Intel Celeron Quad Core 11...,"₹23,990",Intel Celeron Dual Core Processor4 GB LPDDR4 R...,4.2
1,ASUS (2022) Celeron Dual Core - (4 GB/128 GB S...,"₹22,490",Intel Celeron Dual Core Processor4 GB DDR4 RAM...,4.1
2,HP intel Celeron Dual Core - (4 GB/64 GB EMMC ...,"₹20,990",Intel Celeron Dual Core Processor4 GB LPDDR4 R...,3.9
3,Lenovo IdeaPad 3 Intel Core i3 11th Gen - (8 G...,"₹33,990",Intel Core i3 Processor (11th Gen)8 GB DDR4 RA...,4.2
4,Infinix INBook X1 Neo Series Celeron Quad Core...,"₹21,990",Intel Celeron Quad Core Processor4 GB LPDDR4X ...,4.1
...,...,...,...,...
211,acer Extensa Ryzen 5 Quad Core 7520U - (8 GB/5...,NaN,NaN,NaN
212,ASUS ROG Zephyrus G15 (2022) Ryzen 9 Octa Core...,NaN,NaN,NaN
213,ASUS Zenbook 14 OLED (2023) Intel EVO P-Series...,NaN,NaN,NaN
214,Lenovo IdeaPad Ryzen 5 Hexa Core 5600H - (8 GB...,NaN,NaN,NaN
215,Lenovo IdeaPad 3 Intel Core i5 12th Gen - (16 ...,NaN,NaN,NaN

In [18]:
lap = lap.dropna()

In [19]:
lap

,Product Name,Prices,Description,Reviews
0,Infinix Y1 Plus Neo Intel Celeron Quad Core 11...,"₹23,990",Intel Celeron Dual Core Processor4 GB LPDDR4 R...,4.2
1,ASUS (2022) Celeron Dual Core - (4 GB/128 GB S...,"₹22,490",Intel Celeron Dual Core Processor4 GB DDR4 RAM...,4.1
2,HP intel Celeron Dual Core - (4 GB/64 GB EMMC ...,"₹20,990",Intel Celeron Dual Core Processor4 GB LPDDR4 R...,3.9
3,Lenovo IdeaPad 3 Intel Core i3 11th Gen - (8 G...,"₹33,990",Intel Core i3 Processor (11th Gen)8 GB DDR4 RA...,4.2
4,Infinix INBook X1 Neo Series Celeron Quad Core...,"₹21,990",Intel Celeron Quad Core Processor4 GB LPDDR4X ...,4.1
...,...,...,...,...
147,Lenovo IdeaPad 3 Intel Core i3 11th Gen - (8 G...,"₹33,990",Intel Core i3 Processor (11th Gen)8 GB DDR4 RA...,3.6
148,ASUS TUF Gaming F15 Core i5 10th Gen - (8 GB/5...,"₹1,81,001",Intel Core i7 Processor (12th Gen)16 GB LPDDR5...,4.7
149,APPLE 2023 MacBook Pro M2 Pro - (16 GB/1 TB SS...,"₹59,990",AMD Ryzen 7 Octa Core Processor16 GB DDR4 RAM6...,4.5
150,Lenovo Legion 5 Intel Core i5 10th Gen - (8 GB...,"₹31,900",Intel Pentium Quad Core Processor8 GB DDR4 RAM...,4.3
151,Lenovo IdeaPad Slim 3 Intel Core i3 11th Gen -...,"₹33,831",Intel Core i3 Processor (11th Gen)8 GB DDR4 RA...,4.1

In [20]:
lap.to_csv("LAPTOP_UNDER_20000.csv")